Feature/create question page
Helpfy/helpfy-frontend pull request #33
Opened 2022-12-12 23:52 UTC by victorbrandaoa

2022-12-14 01:56 UTC, RuanGOA requested changes
Só fiz uma correção besta, por puro preciosismo xD. De resto, LGTM! Ta dominando bem já :P

2022-12-14 01:56 UTC, RuanGOA commented on src/pages/CreateQuestionPage/index.js
> +import React from "react";
```suggestion
import React, { useState } from "react";
```

2022-12-14 01:56 UTC, RuanGOA commented on src/pages/CreateQuestionPage/index.js
> +  const [questionText, setQuestionText] = React.useState("");
```suggestion
  const [title, setTitle] = useState("");
  const [questionText, setQuestionText] = useState("");
```

2022-12-16 21:19 UTC, victorbrandaoa commented
> Só fiz uma correção besta, por puro preciosismo xD. De resto, LGTM! Ta dominando bem já :P

Valeu hehe!

2022-12-17 00:07 UTC, merged