Feature/ask related features
Helpfy/helpfy-frontend pull request #34
Opened 2022-12-14 01:48 UTC by RuanGOA

Pessoal, primeiramente peço perdão pelo tamanho do PR. A ideia era quebrar bastante, mas acabei esquecendo de commitar uma branch bem importante, e removendo a pasta do repositório, o que me fez ter que refazer o trabalho feito anteriormente.

Nesse PR estou adicionando a página de Questão, e a página de Lista de Questões. Além disso, obviamente vão também os componentes que estão relacionados, como AskCard, CommentCard, AnswerCard, entre outros.

Além disso, corrigi problemas de linter apontados pelo browser, como nome de propriedades css.

2022-12-14 12:28 UTC, gabrielmbs commented
@RuanGOA Está com conflito

2022-12-14 13:46 UTC, gabrielmbs approved these changes
ok

2022-12-14 16:06 UTC, RuanGOA commented
> @RuanGOA Está com conflito

O último commit corrige isso. Era no Router.

2022-12-16 02:40 UTC, victorbrandaoa requested changes
Deixei alguns poucos comentários, a tirar os relacionados com indentação, o resto são apenas dúvidas. Ótima implementação!

2022-12-16 02:40 UTC, victorbrandaoa commented on src/components/AnswerCard/index.js
> +      </Box>
Uma dúvida, como esse é o `AnswerCard` essa parte é referente a alguém comentando a resposta? Ou relacionado a adicionar uma resposta? Porque se for o primeiro caso acho que a nomenclatura deveria ser `Comentar` e não `Responder`.

2022-12-16 02:40 UTC, victorbrandaoa commented on src/components/AskCard/index.js
> +          title="Como corrigir o KDE no FreeBSD?"
Acredito que esse `tittle` deveria vir de `ask`.

2022-12-16 02:40 UTC, victorbrandaoa commented on src/components/CommentCard/index.js
> +export default function CommentCard({ text, user }) {
A indentação desse componente ta mais espaçada que a dos demais.

2022-12-16 02:40 UTC, victorbrandaoa commented on src/components/CommentCard/index.js
> +	);
Uma dúvida, como esse é o `CommentCard`, vai ser possível responder um comentário?

2022-12-16 02:40 UTC, victorbrandaoa commented on src/components/CommentList/index.js
> +export default function CommentList({ comments }) {
A indentação desse componente está mais espaçada que a dos demais.

2022-12-16 02:41 UTC, victorbrandaoa commented
Outra questão que fiquei: o `package-lock.json` deveria subir mesmo? Acredito que deveria ser apenas o `package.json`, não?

2022-12-16 12:29 UTC, RuanGOA commented on src/components/AnswerCard/index.js
> +      </Box>
Bem observado.

2022-12-16 21:13 UTC, victorbrandaoa commented on src/Router.js
> +        <Route exact path={ASKS.route} element={<AsksListPage />} />
Essas duas rotas não estão repetidas? Tipo, ambas usam o mesmo elemento.

2022-12-16 21:16 UTC, victorbrandaoa approved these changes
LGTM!

2022-12-16 22:45 UTC, merged