Add question comments
Helpfy/helpfy-frontend pull request #46
Opened 2022-12-17 19:08 UTC by RuanGOA

Modifiquei os estilos dos comentários. Refatorei algumas partes do que está relacionado a Ask, Answer e Comment. E aproveitei para ajustar algumas coisas que eu observei falhar enquanto testava a aplicação.

2022-12-17 20:12 UTC, victorbrandaoa requested changes
Deixei alguns poucos comentários.

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/AskCard/index.js
> +        addComment={handleComment}
Acredito que esteja faltando o `handleAnswer`.

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/CardInteract/index.js
> +	addComment, //funcao de enviar comentario
Acho interessante remover os comentários depois.

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/CardInteract/index.js
> +			{answering && (
Acho que o nome aqui seria `commenting`, visto que a função usada é o `handleComment`

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/CommentCard/index.js
> -      <Divider sx={{ borderColor: "#F0F0F0" }} />
Remove o import do `Divider`.

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/CardInteract/index.js
> +export default function CardInteractions({
Indentação desse arquivo diferente.

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/CardInteract/index.js
> +						onClick={!resumed && handleUpvote}
Por que a função do `onClick` só é colocada quando esse `resumed` é falso? Qual a semântica disso?

2022-12-17 20:12 UTC, victorbrandaoa commented on src/components/TagList/index.js
> +export default function TagList({ tags }) {
A indentação desse aquivo está diferente.

2022-12-17 21:24 UTC, RuanGOA commented on src/components/CardInteract/index.js
> +						onClick={!resumed && handleUpvote}
O onClick desse componente ativa também a opção de deixar ele "clicável". A ideia em só passar a funcao com o resumed, é para quando ele é usado apenas para exibir os status, e não ser usado como botão.

2022-12-17 21:27 UTC, RuanGOA commented on src/components/AskCard/index.js
> +        addComment={handleComment}
Na verdade não. O input para adicionar uma resposta está no final da página. O que pretendo fazer quando for tratar isso é adicionar um botão "responder", que clicando nele, o usuário é levado ao final da página, e o foco no componente de escrita de markdown é ativado automaticamente.

2022-12-17 21:28 UTC, RuanGOA commented on src/components/CardInteract/index.js
> +	addComment, //funcao de enviar comentario
Deixei os comentários propositalmente para quando for adicionada a lógica, seguir isso como "documentação" e então remover.

2022-12-17 21:28 UTC, RuanGOA commented on src/components/CardInteract/index.js
> +			{answering && (
Boa.

2022-12-17 21:29 UTC, RuanGOA commented on src/components/CommentCard/index.js
> -      <Divider sx={{ borderColor: "#F0F0F0" }} />
Boa

2022-12-19 14:10 UTC, victorbrandaoa approved these changes
LGTM!

2022-12-19 14:10 UTC, victorbrandaoa commented on src/components/AskCard/index.js
> +        addComment={handleComment}
Massa, entendi.

2022-12-19 22:21 UTC, merged