Feature/integration questions route
Helpfy/helpfy-frontend pull request #47
Opened 2022-12-18 21:11 UTC by victorbrandaoa

2022-12-18 21:26 UTC, gabrielmbs requested changes

2022-12-18 21:26 UTC, gabrielmbs commented on src/pages/CreateQuestionPage/form.js
> +      .catch((err) => {
Tenta pegar a mensagem do backend, caso ele não passe aí você coloca uma default.

2022-12-18 21:26 UTC, gabrielmbs commented on src/services/question.js
> +    return api.patch(`/questions/users/${user.id}`, body, {
O patch está funcionando? Testou?

2022-12-18 21:26 UTC, gabrielmbs commented on src/pages/CreateQuestionPage/form.js
> +    if (newTag !== "" && !tags.includes(newTag)) {
Acho que seria interessante adicionar uma notificação informando que não pode colocar tag vazia ou repetida.

2022-12-19 01:54 UTC, victorbrandaoa commented on src/pages/CreateQuestionPage/form.js
> +    if (newTag !== "" && !tags.includes(newTag)) {
Feito.

2022-12-19 01:55 UTC, victorbrandaoa commented on src/pages/CreateQuestionPage/form.js
> +      .catch((err) => {
Feito. Decidi pegar da response, mesmo aquelas estranhas, já que vamos adicionar o tratamento depois, mas qualquer coisa, posso colocar uma mensagem default.

2022-12-19 01:56 UTC, victorbrandaoa commented on src/services/question.js
> +    return api.patch(`/questions/users/${user.id}`, body, {
Não cheguei a testar o update de uma questão, pois não sei como isso vai se dar no front ainda, vai ser uma nova página apenas de edição?

2022-12-19 12:45 UTC, gabrielmbs commented on src/pages/CreateQuestionPage/form.js
> +      .catch((err) => {
O ideal é deixar claro para o cliente

2022-12-19 12:46 UTC, gabrielmbs commented on src/services/question.js
> +    return api.patch(`/questions/users/${user.id}`, body, {
Acredito deva ter um botão que habilita a edição do campo e os botões de salvar, na tela da questão(acredito que ruan está fazendo)

2022-12-19 13:16 UTC, gabrielmbs approved these changes

2022-12-19 13:16 UTC, gabrielmbs commented on src/pages/CreateQuestionPage/form.js
> +        const msg = err.response.data.message;
Coloca como task para o back tratar isso, sem prioridades e trata aqui no front, tipo, ver se é uma mensagem legível e coloca você mesma a mensagem caso não seja

2022-12-19 13:16 UTC, gabrielmbs commented
Ok

2022-12-19 13:22 UTC, victorbrandaoa commented on src/pages/CreateQuestionPage/form.js
> +        const msg = err.response.data.message;
A parte ruim é que eu não tenho como saber qual erro foi, o que eu posso fazer é colocar uma mensagem genérica.

2022-12-19 14:09 UTC, gabrielmbs commented on src/pages/CreateQuestionPage/form.js
> +        const msg = err.response.data.message;
Acho melhor

2022-12-19 23:39 UTC, RuanGOA approved these changes

2022-12-19 23:39 UTC, merged