Fix/render page on input change
Helpfy/helpfy-frontend pull request #48
Opened 2022-12-18 21:51 UTC by RuanGOA

2022-12-18 22:04 UTC, gabrielmbs requested changes

2022-12-18 22:04 UTC, gabrielmbs commented on src/components/CardInteract/index.js
> +export default function CardInteractions({
Esse arquivo está com a formatação errada, quando baixar os plugins: Prettier - Code formatter e o ESLint, para gente manter um padrão no front.
E adiciona isso no seu settings para ele ficar formando automaticamente,
```json
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  ```

2022-12-18 22:04 UTC, gabrielmbs commented on src/components/FormRegister/index.js
> +  const handleSubmit = (event) => {
Isso já foi implementado, acredito que você pegou uma versão antiga do development, faz o pull para conferir, por favor

2022-12-18 22:04 UTC, gabrielmbs commented on src/components/TagList/index.js
> +export default function TagList({ tags }) {
Corrigir formatação desse também

2022-12-18 22:04 UTC, gabrielmbs commented on src/pages/RegisterPage/index.js
>  export default function RegisterPage() {
Só para lembrar que é esse arquivo que está com a versão antiga no seu.

2022-12-19 00:31 UTC, RuanGOA commented on src/components/FormRegister/index.js
> +  const handleSubmit = (event) => {
Eu estava usando uma versão antiga da dev. E isso realmente já foi implementado, o que fiz ai foi extrair para um componente a parte da página, uma refatoração.

2022-12-19 00:32 UTC, RuanGOA commented on src/pages/RegisterPage/index.js
>  export default function RegisterPage() {
Essa branch foi criada justamente para corrigir o problema de renderização a cada mudança de estado. Para isso, refatorei o código das duas páginas.

2022-12-19 13:19 UTC, gabrielmbs approved these changes
ok

2022-12-19 14:25 UTC, victorbrandaoa approved these changes
LGTM!

2022-12-19 22:29 UTC, merged