Filters Logic
Helpfy/helpfy-frontend pull request #59
Opened 2023-02-06 02:15 UTC by RuanGOA

2023-02-06 11:27 UTC, gabrielmbs commented on src/components/FiltersBar/index.js
> +import React, { useState, useContext } from "react";
Não está sendo utilizado o useState
```suggestion
import React, { useContext } from "react";
```

2023-02-06 11:33 UTC, gabrielmbs requested changes

2023-02-06 11:33 UTC, gabrielmbs commented on src/components/CardOptions/index.js
> +        {acceptAnswerOption && (
Esse botão é mostrado para todo mundo? Idealmente seria bom mostrar só para quem criou a pergunta, mas a gente pode deixar isso para uma fix de p2

2023-02-06 11:33 UTC, gabrielmbs commented on src/components/FiltersBar/index.js
> +import React, { useState, useContext } from "react";
Não está sendo utilizado o useState

```suggestion
import React, { useContext } from "react";
```

2023-02-07 00:04 UTC, RuanGOA commented on src/components/CardOptions/index.js
> +        {acceptAnswerOption && (
Pensei exatamente nisso durante o desenvolvimento.

2023-02-07 00:36 UTC, gabrielmbs approved these changes

2023-02-07 00:36 UTC, merged